{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "bad request count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webservice_failed_lookups_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "webservice_request_latency_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "url shortened count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webservice_urls_shortened_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "url shortened rate and redirection rate over time",
   "type": "timeseries",
   "description": "url shortened rate and redirection rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(webservice_urls_shortened_total[10m])",
     "legendFormat": "url shortened rate"
    },
    {
     "expr": "rate(webservice_redirects_total[10m])",
     "legendFormat": "redirection rate"
    }
   ]
  },
  {
   "title": "error 404 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "webservice_failed_lookups_total",
     "legendFormat": "graph"
    }
   ]
  }
 ]
}